# Generated by Django 4.2 on 2024-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The URL path accessed.', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.).', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the request was made.')),
            ],
        ),
    ]
